---
kind: pipeline
name: blueprint
trigger:
  branch:
  - deploy
steps:
- name: build
  image: node:dubnium
  commands:
  - echo -n $NPMRC | base64 -d > /root/.npmrc
  - yarn
  - yarn compile
  - yarn dist:libs
  - rm /root/.npmrc
  environment:
    NPMRC:
     from_secret: NPMRC
- name: publish
  image: node:dubnium
  commands:
  - echo -n $NPMRC | base64 -d > /root/.npmrc
  - npm publish packages/core
  - npm publish packages/icons
  - npm publish packages/datetime
  - npm publish packages/table
  - npm publish packages/select
  - rm /root/.npmrc
  environment:
    NPMRC:
     from_secret: NPMRC

---
kind: signature
hmac: 132192b16865b7129546fd1959bd8707c32e833caef825c3681d4e91d26f4e37

...
