labels:
  hostname: secondary-rwo

when:
  event: push
  branch: deploy

variables:
  - &node_image node:20-alpine
  - &default_backend_options
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 8Gi
            cpu: 2000m
            ephemeral-storage: 10Gi
          limits:
            memory: 12Gi
            cpu: 4000m
            ephemeral-storage: 10Gi

steps:
  - name: build
    image: *node_image
    commands:
      - apk add --update-cache bash
      - corepack enable
      - echo -n $NPMRC | base64 -d > /root/.npmrc
      - yarn
      - yarn compile
      - yarn dist:libs
      - rm /root/.npmrc
    environment:
      NPMRC:
        from_secret: NPMRC_GAR_CI
    <<: *default_backend_options

  - name: publish
    image: *node_image
    commands:
      - apk add --update-cache git openssh
      - echo -n $NPMRC | base64 -d > /root/.npmrc
      - npm publish ./packages/core
      - npm publish ./packages/icons
      - npm publish ./packages/datetime
      - npm publish ./packages/table
      - npm publish ./packages/select
      - npm publish ./packages/datetime2
      - rm /root/.npmrc
    environment:
      NPMRC:
        from_secret: NPMRC_GAR_CI_PRIVATE
    depends_on:
      - build
    <<: *default_backend_options

  - name: docs
    image: *node_image
    commands:
      - apk add --update-cache git openssh
      - corepack enable
      - yarn dist:apps
      - yarn site:clean
      - yarn copy:docs-app
      - mkdir /root/.ssh && echo "$DEPLOY_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      - git config user.email "woodpecker@graphext.com"
      - git config user.name "Woodpecker CI"
      - git remote set-url origin git@github.com:graphext/blueprint.git
      - yarn deploy
    environment:
      DEPLOY_KEY:
        from_secret: DEPLOY_KEY
    depends_on:
      - build
    <<: *default_backend_options
