#
# The setup (just first time):
# docker-compose run bp sh -c 'yarn && yarn compile'
#
# In order to update Markdowns
# docker-compose run bp sh -c 'yarn docs-data'
#
version: '3'
services:
  bp:
    image: development_old
    command: sh -c 'yarn dev'
    working_dir: /hostdata
    volumes:
      - .:/hostdata
      - ~/.npmrc:/root/.npmrc
    ports:
      - "9000:9000"
