#
# The setup (just first time):
# docker-compose run bp sh -c 'ln -s /node_modules ./node_modules; yarn && yarn verify'
#
# In order to update Markdowns
# docker-compose run bp sh -c 'ln -s /node_modules ./node_modules; yarn docs-data'
#
version: '3'
services:
  bp:
    image: development
    command: sh -c 'ln -s /node_modules ./node_modules; yarn dev'
    working_dir: /hostdata
    volumes:
      - .:/hostdata
      - node_modules:/node_modules
    ports:
      - 9100:9000
volumes:
  node_modules:
